name: CI pipeline for building Hashlink 

on:
  push:
    branches: [ linux-ci ]

# Tips for Linux
#
# We build the system on Ubuntu (but not SteamRT). This is because
# none of the compilers with SteamRT can correctly compile
# libuv (builtin 4.8.8 - no stdatomic.h, clang 3.6/3.8 and gcc-9 stuck
# at compilation.
#
# For a purpose of maximizing compatibility, we maintain our
# dependencies as much as possible.
#
# Inc case we use updated SteamRT in the future, We can use 
# addnab/docker-run-action@v3 job to run commnds in container.
# REF: https://aschmelyun.com/blog/using-docker-run-inside-of-github-actions/
#
# NOTE for xmake: We can't default xmake ppa because Steam Runtime
# defines its own /etc/lsb-release to SteamRT. We have to build it
# from source.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout build scripts
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - name: Install xmake tool
        run: |
              git clone https://github.com/xmake-io/xmake
              cd ./xmake
              git submodule update --init --recursive .
              ./configure --prefix=/hashbld/xmake/buildroot > /dev/null 2>&1
              make > /dev/null 2>&1
              make install > /dev/null 2>&1
      - name: Build Linux (x86_64)
        run: |
              bash clone-code.sh
              ./xmake/buildroot/bin/xmake global --root --yes --theme=plain
              ./xmake/buildroot/bin/xmake config --root --yes --verbose -a x86_64 -p linux
              ./xmake/buildroot/bin/xmake build --root --yes --verbose libhl
              # ./xmake/buildroot/bin/xmake build --root --yes hl
              # ./xmake/buildroot/bin/xmake build --root --yes fmt
              # ./xmake/buildroot/bin/xmake build --root --yes sqlite
              # ./xmake/buildroot/bin/xmake build --root --yes ssl
              # ./xmake/buildroot/bin/xmake build --root --yes ui
              # ./xmake/buildroot/bin/xmake build --root --yes sdl
              # ./xmake/buildroot/bin/xmake build --root --yes openal
              # ./xmake/buildroot/bin/xmake build --root --yes uv
