name: CI pipeline for building Hashlink 

on:
  push:
    branches: [ linux-ci ]

# Linux
# We use Steam Runtime image to build hashlink from source code.
# The job uses addnab/docker-run-action@v3 instead of jobs.build.container
# introduced in official doc, because the code checkout step
# actions/checkout@v3 uses a newer GLIBC_2.16 and GLIB_2.17 version,
# which is unavailable in Steam runtime.
#
# REF: https://aschmelyun.com/blog/using-docker-run-inside-of-github-actions/
#
# NOTE 2: We can't default xmake ppa because Steam Runtime defines its
# own /etc/lsb-release to SteamRT. We have to build it from source.
#
# TODO: Shall we use clang 3.8 (integrated) to build Steam version?
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout build scripts
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - name: Build in Steam Runtime image (x86_64)
        uses: addnab/docker-run-action@v3
        with:
          image: registry.gitlab.steamos.cloud/steamrt/scout/sdk
          options: --cpus 1 -v ${{github.workspace}}:/hashbld
          run: |
              apt update
              apt -y install unzip > /dev/null 2>&1
              cd /hashbld
              git clone https://github.com/xmake-io/xmake
              cd /hashbld/xmake
              git submodule update --init --recursive .
              ./configure --prefix=/hashbld/xmake/buildroot > /dev/null 2>&1
              make > /dev/null 2>&1
              make install > /dev/null 2>&1
              cd /hashbld
              bash clone-code.sh
              /hashbld/xmake/buildroot/bin/xmake global --root --theme=plain
              /hashbld/xmake/buildroot/bin/xmake config --root -a x86_64
              /hashbld/xmake/buildroot/bin/xmake config --sdk=/usr/lib/llvm-3.8/lib/clang --toolchain=steamrt-clang38
              export steamrt=yes
              /hashbld/xmake/buildroot/bin/xmake build --root --yes hl

              
# /hashbld/xmake/buildroot/bin/xmake build --root --yes fmt
# /hashbld/xmake/buildroot/bin/xmake build --root --yes openal
# /hashbld/xmake/buildroot/bin/xmake build --root --yes sdl
# /hashbld/xmake/buildroot/bin/xmake build --root --yes sqlite
# /hashbld/xmake/buildroot/bin/xmake build --root --yes ssl
# /hashbld/xmake/buildroot/bin/xmake build --root --yes uv
# /hashbld/xmake/buildroot/bin/xmake build --root --yes ui
