name: CI pipeline for building Hashlink 

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.steamos.cloud/steamrt/scout/sdk
      volumes:
        - ${{github.workspace}}:/hashbld
      options: --cpus 1
    steps:
      - name: checkout build scripts
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - name: install xmake tool
        run: (add-apt-repository ppa:xmake-io/xmake && apt update && apt install xmake)
      - name: checkout hashlink source code
        run: (cd /hashbld && sh clone-code.sh)
      - name: Run xmake to build project
        run: (cd /hashbld && xmake build --verbose --yes --all)
