name: CI pipeline for building Hashlink 

on:
  push:
    branches: [ main ]

# Linux
# We use Steam Runtime image to build hashlink from source code.
# The job uses addnab/docker-run-action@v3 instead of jobs.build.container
# introduced in official doc, because the code checkout step
# actions/checkout@v3 uses a newer GLIBC_2.16 and GLIB_2.17 version,
# which is unavailable in Steam runtime.
#
# REF: https://aschmelyun.com/blog/using-docker-run-inside-of-github-actions/
#
# NOTE 2: We can't default xmake ppa because Steam Runtime defines its
# own /etc/lsb-release to SteamRT. We have to build it from source.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout build scripts
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - name: Build in Steam Runtime image
        uses: addnab/docker-run-action@v3
        with:
          image: registry.gitlab.steamos.cloud/steamrt/scout/sdk
          options: --cpus 1 -v ${{github.workspace}}:/hashbld
          run: |
              apt update
              apt -y install unzip
              cd /hashbld
              git clone https://github.com/xmake-io/xmake
              cd /hashbld/xmake
              git submodule update --init --recursive .
              ./configure --prefix=/hashbld/xmake/buildroot
              make
              make install
              cd /hashbld
              bash clone-code.sh
              /hashbld/xmake/buildroot/bin/xmake build --root --verbose --yes --all
